apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 871313051482.dkr.ecr.us-east-1.amazonaws.com/orders:6c87ba028b21d535f3b27cf8154572a379a898ca
          ports:
            - containerPort: 3005
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3005"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: boutique-jwt
                  key: JWT_SECRET
            - name: PRODUCTS_SERVICE_URL
              value: "http://product-service:3003"

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: boutique
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
